import type { Metadata } from "next";

import { Roboto } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Spotify Thing",
  description: "Generated by create next app",
};

const roboto = Roboto({
  display: "swap",
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
